<?php

    defined('INSIDE') OR exit('No direct script access allowed');

    $lang['metal'] = 'Metal';
    $lang['crystal'] = 'Crystal';
    $lang['deuterium'] = 'Deuterium';
    $lang['energy'] = 'Energy';

    $lang['metal_mine'] = 'Metal Mine';
    $lang['crystal_mine'] = 'Crystal Mine';
    $lang['deuterium_synthesizer'] = 'Deuterium Synthesizer';
    $lang['solar_plant'] = 'Solar Plant';
    $lang['fusion_reactor'] = 'Fusion Reactor';
    $lang['robotic_factory'] = 'Robotic Factory';
    $lang['nanite_factory'] = 'Nanite Factory';
    $lang['shipyard'] = 'Shipyard';
    $lang['metal_storage'] = 'Metal Storage';
    $lang['crystal_storage'] = 'Crystal Storage';
    $lang['deuterium_storage'] = 'Deuterium Storage';
    $lang['research_lab'] = 'Research Lab';
    $lang['terraformer'] = 'Terraformer';
    $lang['alliance_depot'] = 'Alliance Depot';
    $lang['missile_silo'] = 'Missile Silo';

    $lang['lunar_base'] = 'Lunar Base';
    $lang['sensor_phalanx'] = 'Sonsor Phalanx';
    $lang['jump_gate'] = 'Jump Gate';

    $lang['espionage_tech'] = 'Espionage Technology';
    $lang['computer_tech'] = 'Computer Technology';
    $lang['weapon_tech'] = 'Weapons Technology';
    $lang['armour_tech'] = 'Armour Technology';
    $lang['shielding_tech'] = 'Shielding Technology';
    $lang['energy_tech'] = 'Energy Technology';
    $lang['hyperspace_tech'] = 'Hyperspace Technology';
    $lang['combustion_drive_tech'] = 'Combustion Drive';
    $lang['impulse_drive_tech'] = 'Impulse Drive';
    $lang['hyperspace_drive_tech'] = 'Hyperspace Drive';
    $lang['laser_tech'] = 'Laser Technology';
    $lang['ion_tech'] = 'Ion Technology';
    $lang['plasma_tech'] = 'Plasma Technology';
    $lang['intergalactic_research_tech'] = 'Intergalactic Research Network';
    $lang['graviton_tech'] = 'Graviton Technology';

    $lang['small_cargo_ship'] = 'Small Cargo Ship';
    $lang['large_cargo_ship'] = 'Large Cargo Ship';
    $lang['light_fighter'] = 'Light Fighter';
    $lang['heavy_fighter'] = 'Heavy Fighter';
    $lang['cruiser'] = 'Cruiser';
    $lang['battleship'] = 'Battleship';
    $lang['colony_ship'] = 'Colony Ship';
    $lang['recycler'] = 'Recycler';
    $lang['espionage_probe'] = 'Espionage Probe';
    $lang['bomber'] = 'Bomber';
    $lang['solar_satellite'] = 'Solar Satellite';
    $lang['destroyer'] = 'Destroyer';
    $lang['battlecruiser'] = 'Battlecruiser';
    $lang['deathstar'] = 'Deathstar';

    $lang['rocket_launcher'] = '';
    $lang['light_laser'] = '';
    $lang['heavy_laser'] = '';
    $lang['gauss_cannon'] = '';
    $lang['ion_cannon'] = '';
    $lang['plasma_turret'] = '';
    $lang['small_shield_dome'] = '';
    $lang['large_shield_dome'] = '';
    $lang['anti_ballistic_missile'] = '';
    $lang['interplanetary_missile'] = '';

    // planet
    $lang['metal_mine_descr'] = 'Metal is the main resource for conducting research and the construction of buildings, ships, and defensive units.';
    $lang['crystal_mine_descr'] = 'Crystal is the main resource for electronic components and alloys. It is also crucial in conducting research and construction of buildings, ships and defensive structures.';
    $lang['deuterium_synthesizer_descr'] = 'Deuterium is a heavy isotope of hydrogen and not very abundant. It is predominantly used as fuel but it is also needed for some types of research and the construction of some ships, defense, and buildings. ';
    $lang['solar_plant_descr'] = 'Each mine requires energy to function, which is produced primarily by the Solar Plant.';
    $lang['fusion_reactor_descr'] = 'This reactor is also used for energy production. The energy is generated by the fusion of two deuterium atoms into one helium atom.';
    $lang['robotic_factory_descr'] = 'With the help of the Robotics Factory, buildings can be upgraded faster.';
    $lang['nanite_factory_descr'] = 'This halves the construction time of ships, defensive structures, and buildings.';
    $lang['shipyard_descr'] = 'This facility is necessary for the construction of both ships and defensive units, with some requiring a certain level of the shipyard first.';
    $lang['metal_storage_descr'] = 'This storage facility is used to store Metal. If the storage is full, production will be stopped.';
    $lang['crystal_storage_descr'] = 'This facility is required to continue the Crystal production. If it is full the production will be stopped.';
    $lang['deuterium_storage_descr'] = 'Like the storages the Deuterium Tank is required to allow further production.';
    $lang['research_lab_descr'] = 'This is necessary to research new technologies. The higher the level, the more technologies will be activated and the shorter the research time will be.';
    $lang['terraformer_descr'] = 'The Terraformer is needed to expand nearly developed planets. 5 free fields are added per level, plus an additional field every 2 levels, but you need energy for the construction.';
    $lang['alliance_depot_descr'] = 'With this facility, it is possible to support holding fleets with deuterium via support rockets. Higher levels will allow friendly fleets to remain in orbit longer.';
    $lang['missile_silo_descr'] = 'The Missile Silo is used to build Anti-Ballistic Missiles and Interplanetary Missiles.';
    
    // moon
    $lang['lunar_base_descr'] = 'This structure can only be built on a moon. It is necessary to get more building slots, since a moon consists of only one field at the beginning.';
    $lang['sensor_phalanx_descr'] = 'This facility can, like the Lunar Base, only be built on a moon.';
    $lang['jump_gate_descr'] = 'The Jump Gate can also only be built on a moon. It is utilized to instantaneously send fleets from one moon to another. After a jump, the start Gate and target Gate have to cool down for one hour before they can be used again.';

    // techs
    $lang['espionage_tech_descr'] = '';
    $lang['computer_tech_descr'] = '';
    $lang['weapon_tech_descr'] = '';
    $lang['armour_tech_descr'] = '';
    $lang['shielding_tech_descr'] = '';
    $lang['energy_tech_descr'] = '';
    $lang['hyperspace_tech_descr'] = '';
    $lang['combustion_drive_tech_descr'] = '';
    $lang['impulse_drive_tech_descr'] = '';
    $lang['hyperspace_drive_tech_descr'] = '';
    $lang['laser_tech_descr'] = '';
    $lang['ion_tech_descr'] = '';
    $lang['plasma_tech_descr'] = '';
    $lang['intergalactic_research_tech_descr'] = '';
    $lang['graviton_tech_descr'] = '';
    
    
    $lang['small_cargo_ship_descr'] = '';
    $lang['large_cargo_ship_descr'] = '';
    $lang['light_fighter_descr'] = '';
    $lang['heavy_fighter_descr'] = '';
    $lang['cruiser_descr'] = '';
    $lang['battleship_descr'] = '';
    $lang['colony_ship_descr'] = '';
    $lang['recycler_descr'] = '';
    $lang['espionage_probe_descr'] = '';
    $lang['bomber_descr'] = '';
    $lang['solar_satellite_descr'] = '';
    $lang['destroyer_descr'] = '';
    $lang['battlecruiser_descr'] = '';
    $lang['deathstar_descr'] = '';
    $lang['rocket_launcher_descr'] = '';
    $lang['light_laser_descr'] = '';
    $lang['heavy_laser_descr'] = '';
    $lang['gauss_cannon_descr'] = '';
    $lang['ion_cannon_descr'] = '';
    $lang['plasma_turret_descr'] = '';
    $lang['small_shield_dome_descr'] = '';
    $lang['large_shield_dome_descr'] = '';
    $lang['anti_ballistic_missile_descr'] = '';
    $lang['interplanetary_missile_descr'] = '';
